//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollAppsAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollDataEntities : DbContext
    {
        public PayrollDataEntities()
            : base("name=PayrollDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BirthDay> BirthDays { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FormerStaff> FormerStaffs { get; set; }
        public virtual DbSet<Hmo> Hmoes { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<PaySlip> PaySlips { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
