//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollAppsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> Transport { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Dressing { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
